"""Verified employer board registry.

Every entry here was confirmed against the live board on 2026-07-22 — this
file records what actually answered, not what we hope exists. `canada_jobs`
is the Canada-matching count observed at verification time and is indicative
only; the real number changes daily.

Regenerate with scripts/discover_boards.py.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class Board:
    employer: str
    connector: str
    external_id: str
    config: dict = field(default_factory=dict)
    verified_on: str = "2026-07-22"
    observed_jobs: int = 0
    observed_canada_jobs: int = 0


BOARDS: list[Board] = [
    Board("Affirm", "greenhouse", "affirm", 
          observed_jobs=173, observed_canada_jobs=60),
    Board("Instacart", "greenhouse", "instacart", 
          observed_jobs=125, observed_canada_jobs=53),
    Board("Stripe", "greenhouse", "stripe", 
          observed_jobs=527, observed_canada_jobs=49),
    Board("1Password", "ashby", "1password", 
          observed_jobs=65, observed_canada_jobs=46),
    Board("Tenstorrent", "greenhouse", "tenstorrent", 
          observed_jobs=131, observed_canada_jobs=45),
    Board("Cohere", "ashby", "cohere", 
          observed_jobs=137, observed_canada_jobs=44),
    Board("Lyft", "greenhouse", "lyft", 
          observed_jobs=147, observed_canada_jobs=44),
    Board("Samsara", "greenhouse", "samsara", 
          observed_jobs=326, observed_canada_jobs=43),
    Board("Brex", "greenhouse", "brex", 
          observed_jobs=275, observed_canada_jobs=41),
    Board("Jobber", "ashby", "jobber", 
          observed_jobs=46, observed_canada_jobs=37),
    Board("Geotab", "greenhouse", "geotab", 
          observed_jobs=103, observed_canada_jobs=36),
    Board("GitLab", "greenhouse", "gitlab", 
          observed_jobs=179, observed_canada_jobs=36),
    Board("Waabi", "lever", "waabi", 
          observed_jobs=58, observed_canada_jobs=32),
    Board("Wealthsimple", "ashby", "wealthsimple", 
          observed_jobs=32, observed_canada_jobs=32),
    Board("Mejuri", "greenhouse", "mejuri", 
          observed_jobs=142, observed_canada_jobs=27),
    Board("Asana", "greenhouse", "asana", 
          observed_jobs=147, observed_canada_jobs=26),
    Board("Databricks", "greenhouse", "databricks", 
          observed_jobs=802, observed_canada_jobs=24),
    Board("MongoDB", "greenhouse", "mongodb", 
          observed_jobs=397, observed_canada_jobs=23),
    Board("Reddit", "greenhouse", "reddit", 
          observed_jobs=192, observed_canada_jobs=22),
    Board("D2L", "greenhouse", "d2l", 
          observed_jobs=27, observed_canada_jobs=19),
    Board("Pinterest", "greenhouse", "pinterest", 
          observed_jobs=193, observed_canada_jobs=15),
    Board("Harvey", "ashby", "harvey", 
          observed_jobs=348, observed_canada_jobs=13),
    Board("Trulioo", "ashby", "trulioo", 
          observed_jobs=26, observed_canada_jobs=13),
    Board("Faire", "greenhouse", "faire", 
          observed_jobs=66, observed_canada_jobs=12),
    Board("Float", "ashby", "float", 
          observed_jobs=12, observed_canada_jobs=12),
    Board("Dropbox", "greenhouse", "dropbox", 
          observed_jobs=32, observed_canada_jobs=11),
    Board("Robinhood", "greenhouse", "robinhood", 
          observed_jobs=116, observed_canada_jobs=11),
    Board("Sentry", "ashby", "sentry", 
          observed_jobs=50, observed_canada_jobs=11),
    Board("Coinbase", "greenhouse", "coinbase", 
          observed_jobs=155, observed_canada_jobs=10),
    Board("ApplyDigital", "lever", "applydigital", 
          observed_jobs=25, observed_canada_jobs=9),
    Board("Snowflake", "ashby", "snowflake", 
          observed_jobs=411, observed_canada_jobs=9),
    Board("Hootsuite", "greenhouse", "hootsuite", 
          observed_jobs=18, observed_canada_jobs=8),
    Board("Anthropic", "greenhouse", "anthropic", 
          observed_jobs=415, observed_canada_jobs=7),
    Board("Twilio", "greenhouse", "twilio", 
          observed_jobs=180, observed_canada_jobs=7),
    Board("Vanta", "ashby", "vanta", 
          observed_jobs=104, observed_canada_jobs=6),
    Board("Confluent", "ashby", "confluent", 
          observed_jobs=33, observed_canada_jobs=5),
    Board("Gusto", "greenhouse", "gusto", 
          observed_jobs=80, observed_canada_jobs=5),
    Board("Sierra", "ashby", "sierra", 
          observed_jobs=165, observed_canada_jobs=5),
    Board("Fivetran", "greenhouse", "fivetran", 
          observed_jobs=194, observed_canada_jobs=4),
    Board("Flexport", "greenhouse", "flexport", 
          observed_jobs=151, observed_canada_jobs=3),
    Board("Thinkific", "greenhouse", "thinkific", 
          observed_jobs=3, observed_canada_jobs=3),
    Board("Thinkific", "ashby", "thinkific", 
          observed_jobs=4, observed_canada_jobs=3),
    Board("Verkada", "greenhouse", "verkada", 
          observed_jobs=273, observed_canada_jobs=3),
    Board("Datadog", "greenhouse", "datadog", 
          observed_jobs=419, observed_canada_jobs=2),
    Board("DeepGenomics", "lever", "deepgenomics", 
          observed_jobs=2, observed_canada_jobs=2),
    Board("ElevenLabs", "ashby", "elevenlabs", 
          observed_jobs=210, observed_canada_jobs=2),
    Board("Loopio", "ashby", "loopio", 
          observed_jobs=4, observed_canada_jobs=2),
    Board("Amplitude", "greenhouse", "amplitude", 
          observed_jobs=45, observed_canada_jobs=1),
    Board("BenchSci", "lever", "benchsci", 
          observed_jobs=1, observed_canada_jobs=1),
    Board("Ramp", "ashby", "ramp", 
          observed_jobs=121, observed_canada_jobs=1),
    Board("Abridge", "ashby", "abridge", 
          observed_jobs=43, observed_canada_jobs=0),
    Board("Amplitude", "ashby", "amplitude", 
          observed_jobs=45, observed_canada_jobs=0),
    Board("AssemblyAI", "greenhouse", "assemblyai", 
          observed_jobs=10, observed_canada_jobs=0),
    Board("Baseten", "ashby", "baseten", 
          observed_jobs=68, observed_canada_jobs=0),
    Board("Benchling", "ashby", "benchling", 
          observed_jobs=49, observed_canada_jobs=0),
    Board("Blue", "lever", "blue", 
          observed_jobs=7, observed_canada_jobs=0),
    Board("BlueDot", "ashby", "bluedot", 
          observed_jobs=4, observed_canada_jobs=0),
    Board("Character", "ashby", "character", 
          observed_jobs=16, observed_canada_jobs=0),
    Board("Cloudflare", "greenhouse", "cloudflare", 
          observed_jobs=271, observed_canada_jobs=0),
    Board("Cursor", "ashby", "cursor", 
          observed_jobs=120, observed_canada_jobs=0),
    Board("D2L", "lever", "d2l", 
          observed_jobs=5, observed_canada_jobs=0),
    Board("Dapper", "ashby", "dapper", 
          observed_jobs=19, observed_canada_jobs=0),
    Board("Deepgram", "ashby", "deepgram", 
          observed_jobs=72, observed_canada_jobs=0),
    Board("Discord", "greenhouse", "discord", 
          observed_jobs=53, observed_canada_jobs=0),
    Board("Duolingo", "greenhouse", "duolingo", 
          observed_jobs=59, observed_canada_jobs=0),
    Board("Figma", "greenhouse", "figma", 
          observed_jobs=172, observed_canada_jobs=0),
    Board("Inngest", "ashby", "inngest", 
          observed_jobs=1, observed_canada_jobs=0),
    Board("Kira", "ashby", "kira", 
          observed_jobs=11, observed_canada_jobs=0),
    Board("Koho", "ashby", "koho", 
          observed_jobs=12, observed_canada_jobs=0),
    Board("LaunchDarkly", "greenhouse", "launchdarkly", 
          observed_jobs=36, observed_canada_jobs=0),
    Board("Lightspeed", "ashby", "lightspeed", 
          observed_jobs=4, observed_canada_jobs=0),
    Board("Linear", "ashby", "linear", 
          observed_jobs=24, observed_canada_jobs=0),
    Board("Mapsted", "lever", "mapsted", 
          observed_jobs=2, observed_canada_jobs=0),
    Board("Miro", "ashby", "miro", 
          observed_jobs=42, observed_canada_jobs=0),
    Board("Modal", "ashby", "modal", 
          observed_jobs=32, observed_canada_jobs=0),
    Board("Neon", "lever", "neon", 
          observed_jobs=11, observed_canada_jobs=0),
    Board("Neon", "ashby", "neon", 
          observed_jobs=6, observed_canada_jobs=0),
    Board("Notion", "ashby", "notion", 
          observed_jobs=139, observed_canada_jobs=0),
    Board("Nuro", "greenhouse", "nuro", 
          observed_jobs=97, observed_canada_jobs=0),
    Board("OpenAI", "ashby", "openai", 
          observed_jobs=735, observed_canada_jobs=0),
    Board("Perplexity", "ashby", "perplexity", 
          observed_jobs=80, observed_canada_jobs=0),
    Board("Plaid", "ashby", "plaid", 
          observed_jobs=119, observed_canada_jobs=0),
    Board("PlanetScale", "greenhouse", "planetscale", 
          observed_jobs=8, observed_canada_jobs=0),
    Board("Railway", "ashby", "railway", 
          observed_jobs=9, observed_canada_jobs=0),
    Board("Render", "ashby", "render", 
          observed_jobs=31, observed_canada_jobs=0),
    Board("Replit", "ashby", "replit", 
          observed_jobs=93, observed_canada_jobs=0),
    Board("Resend", "ashby", "resend", 
          observed_jobs=9, observed_canada_jobs=0),
    Board("Ritual", "greenhouse", "ritual", 
          observed_jobs=15, observed_canada_jobs=0),
    Board("Runway", "ashby", "runway", 
          observed_jobs=4, observed_canada_jobs=0),
    Board("SoFi", "greenhouse", "sofi", 
          observed_jobs=61, observed_canada_jobs=0),
    Board("Solutions", "greenhouse", "solutions", 
          observed_jobs=22, observed_canada_jobs=0),
    Board("Supabase", "ashby", "supabase", 
          observed_jobs=55, observed_canada_jobs=0),
    Board("Vercel", "greenhouse", "vercel", 
          observed_jobs=80, observed_canada_jobs=0),
    Board(
        "TD Bank", "workday", "td",
        config={"tenant": "td", "wd": 3, "site": "TD_Bank_Careers", "company_name": "TD Bank"},
    ),
    Board(
        "BMO", "workday", "bmo",
        config={"tenant": "bmo", "wd": 3, "site": "External", "company_name": "BMO"},
    ),
    Board(
        "CIBC", "workday", "cibc",
        config={"tenant": "cibc", "wd": 3, "site": "search", "company_name": "CIBC"},
    ),
    Board(
        "Manulife", "workday", "manulife",
        config={"tenant": "manulife", "wd": 3, "site": "MFCJH_Jobs", "company_name": "Manulife"},
    ),
    Board(
        "Sun Life", "workday", "sunlife",
        config={"tenant": "sunlife", "wd": 3, "site": "Experienced", "company_name": "Sun Life"},
    ),
]

BY_EMPLOYER: dict[str, Board] = {b.employer.lower(): b for b in BOARDS}


def boards_for(connector: str) -> list[Board]:
    return [b for b in BOARDS if b.connector == connector]


def canada_heavy(min_canada: int = 10) -> list[Board]:
    """Boards that actually showed meaningful Canadian volume."""
    return [b for b in BOARDS if b.observed_canada_jobs >= min_canada]
