"""ranking v2: company evidence, role classification, priority scores

Revision ID: 3f2f9b30e4a1
Revises: 66c10fba84b2
Create Date: 2026-07-22 14:07:34.593116
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3f2f9b30e4a1'
down_revision: Union[str, None] = '66c10fba84b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_evidence',
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('source_type', sa.String(length=60), nullable=False),
    sa.Column('grade', sa.String(length=1), nullable=False),
    sa.Column('supports_dimension', sa.String(length=60), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('still_valid', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_evidence_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_evidence_supports_dimension'), ['supports_dimension'], unique=False)

    op.create_table('company_personal_overrides',
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('personal_tier', sa.String(length=2), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=False),
    sa.Column('user_confirmed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_personal_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_personal_overrides_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_personal_overrides_user_id'), ['user_id'], unique=False)

    op.create_table('company_research_runs',
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('steps_completed', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('needs_research', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_research_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_research_runs_company_id'), ['company_id'], unique=False)

    op.create_table('company_score_versions',
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('formula_version', sa.String(length=20), nullable=False),
    sa.Column('known_evidence_score', sa.Float(), nullable=False),
    sa.Column('evidence_coverage', sa.Float(), nullable=False),
    sa.Column('conservative_score', sa.Float(), nullable=False),
    sa.Column('system_tier', sa.String(length=2), nullable=False),
    sa.Column('tier_status', sa.String(length=20), nullable=False),
    sa.Column('dimension_scores', sa.JSON(), nullable=False),
    sa.Column('risk_flags', sa.JSON(), nullable=False),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_score_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_score_versions_company_id'), ['company_id'], unique=False)

    op.create_table('learning_suggestions',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('supporting_data', sa.JSON(), nullable=False),
    sa.Column('before_weights', sa.JSON(), nullable=False),
    sa.Column('after_weights', sa.JSON(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by_user', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rolled_back', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_suggestions_user_id'), ['user_id'], unique=False)

    op.create_table('application_priority_scores',
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('ranking_mode', sa.String(length=20), nullable=False),
    sa.Column('formula_version', sa.String(length=20), nullable=False),
    sa.Column('weights_version', sa.String(length=40), nullable=False),
    sa.Column('eligibility_gate', sa.String(length=10), nullable=False),
    sa.Column('company_tier', sa.String(length=2), nullable=False),
    sa.Column('company_tier_display', sa.String(length=10), nullable=False),
    sa.Column('role_band', sa.String(length=2), nullable=False),
    sa.Column('role_type', sa.String(length=60), nullable=False),
    sa.Column('company_platform_value', sa.Float(), nullable=False),
    sa.Column('role_strategic_value', sa.Float(), nullable=False),
    sa.Column('current_candidate_fit', sa.Float(), nullable=False),
    sa.Column('team_project_quality', sa.Float(), nullable=False),
    sa.Column('career_optionality', sa.Float(), nullable=False),
    sa.Column('evidence_coverage', sa.Float(), nullable=False),
    sa.Column('application_priority', sa.Float(), nullable=False),
    sa.Column('opportunity_estimate', sa.String(length=80), nullable=False),
    sa.Column('recommendation', sa.String(length=40), nullable=False),
    sa.Column('interaction_rule', sa.String(length=120), nullable=False),
    sa.Column('why', sa.JSON(), nullable=False),
    sa.Column('why_not', sa.JSON(), nullable=False),
    sa.Column('unknowns', sa.JSON(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('manually_overridden', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_priority_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_priority_scores_application_priority'), ['application_priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_priority_scores_eligibility_gate'), ['eligibility_gate'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_priority_scores_formula_version'), ['formula_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_priority_scores_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_priority_scores_user_id'), ['user_id'], unique=False)

    op.create_table('pairwise_preferences',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('chosen_job_id', sa.String(length=32), nullable=False),
    sa.Column('rejected_job_id', sa.String(length=32), nullable=False),
    sa.Column('chosen_tier', sa.String(length=2), nullable=True),
    sa.Column('rejected_tier', sa.String(length=2), nullable=True),
    sa.Column('chosen_band', sa.String(length=2), nullable=True),
    sa.Column('rejected_band', sa.String(length=2), nullable=True),
    sa.Column('context', sa.String(length=60), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chosen_job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['rejected_job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pairwise_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pairwise_preferences_user_id'), ['user_id'], unique=False)

    op.create_table('role_classifications',
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('role_type', sa.String(length=60), nullable=False),
    sa.Column('band', sa.String(length=2), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('technical_density', sa.Float(), nullable=False),
    sa.Column('transferability', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('signals_positive', sa.JSON(), nullable=False),
    sa.Column('signals_negative', sa.JSON(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('formula_version', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role_classifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_classifications_band'), ['band'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_classifications_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_classifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_classifications_job_id'))
        batch_op.drop_index(batch_op.f('ix_role_classifications_band'))

    op.drop_table('role_classifications')
    with op.batch_alter_table('pairwise_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pairwise_preferences_user_id'))

    op.drop_table('pairwise_preferences')
    with op.batch_alter_table('application_priority_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_priority_scores_user_id'))
        batch_op.drop_index(batch_op.f('ix_application_priority_scores_job_id'))
        batch_op.drop_index(batch_op.f('ix_application_priority_scores_formula_version'))
        batch_op.drop_index(batch_op.f('ix_application_priority_scores_eligibility_gate'))
        batch_op.drop_index(batch_op.f('ix_application_priority_scores_application_priority'))

    op.drop_table('application_priority_scores')
    with op.batch_alter_table('learning_suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_suggestions_user_id'))

    op.drop_table('learning_suggestions')
    with op.batch_alter_table('company_score_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_score_versions_company_id'))

    op.drop_table('company_score_versions')
    with op.batch_alter_table('company_research_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_research_runs_company_id'))

    op.drop_table('company_research_runs')
    with op.batch_alter_table('company_personal_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_personal_overrides_user_id'))
        batch_op.drop_index(batch_op.f('ix_company_personal_overrides_company_id'))

    op.drop_table('company_personal_overrides')
    with op.batch_alter_table('company_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_evidence_supports_dimension'))
        batch_op.drop_index(batch_op.f('ix_company_evidence_company_id'))

    op.drop_table('company_evidence')
    # ### end Alembic commands ###
