"""initial schema

Revision ID: 65256e678135
Revises: 
Create Date: 2026-07-21 21:43:50.945188
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '65256e678135'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.String(length=32), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('model_run_id', sa.String(length=32), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('entry_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('size', sa.String(length=40), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_normalized_name'), ['normalized_name'], unique=False)

    op.create_table('model_runs',
    sa.Column('purpose', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('data_scope', sa.String(length=255), nullable=True),
    sa.Column('pii_minimized', sa.Boolean(), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('mfa_secret', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('application_preferences',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('locations', sa.JSON(), nullable=False),
    sa.Column('remote_pref', sa.String(length=20), nullable=True),
    sa.Column('min_salary', sa.Float(), nullable=True),
    sa.Column('salary_currency', sa.String(length=8), nullable=True),
    sa.Column('company_sizes', sa.JSON(), nullable=False),
    sa.Column('industries', sa.JSON(), nullable=False),
    sa.Column('target_roles', sa.JSON(), nullable=False),
    sa.Column('dealbreakers', sa.JSON(), nullable=False),
    sa.Column('weight_overrides', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('provenance', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('user_confirmed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_preferences_user_id'), ['user_id'], unique=False)

    op.create_table('candidate_education',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('school', sa.String(length=255), nullable=True),
    sa.Column('degree', sa.String(length=120), nullable=True),
    sa.Column('field', sa.String(length=120), nullable=True),
    sa.Column('start_date', sa.String(length=20), nullable=True),
    sa.Column('end_date', sa.String(length=20), nullable=True),
    sa.Column('gpa', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('provenance', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('user_confirmed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_education', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_education_user_id'), ['user_id'], unique=False)

    op.create_table('candidate_experiences',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.String(length=20), nullable=True),
    sa.Column('end_date', sa.String(length=20), nullable=True),
    sa.Column('bullets', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('provenance', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('user_confirmed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_experiences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_experiences_user_id'), ['user_id'], unique=False)

    op.create_table('candidate_profiles',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('links', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('provenance', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('user_confirmed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_profiles_user_id'), ['user_id'], unique=False)

    op.create_table('candidate_projects',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tech', sa.JSON(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('provenance', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('user_confirmed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_projects_user_id'), ['user_id'], unique=False)

    op.create_table('candidate_skills',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('proficiency', sa.String(length=40), nullable=True),
    sa.Column('years', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('provenance', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('user_confirmed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_skills_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_skills_user_id'), ['user_id'], unique=False)

    op.create_table('company_aliases',
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_aliases_alias'), ['alias'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_aliases_company_id'), ['company_id'], unique=False)

    op.create_table('company_career_pages',
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('ats_type', sa.String(length=40), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_career_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_career_pages_company_id'), ['company_id'], unique=False)

    op.create_table('company_domains',
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    with op.batch_alter_table('company_domains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_domains_company_id'), ['company_id'], unique=False)

    op.create_table('documents',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('sensitivity_level', sa.String(length=20), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('provenance', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('user_confirmed', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_user_id'), ['user_id'], unique=False)

    op.create_table('email_connections',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('secret_ref', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_connections_user_id'), ['user_id'], unique=False)

    op.create_table('job_sources',
    sa.Column('connector_key', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=True),
    sa.Column('source_priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('etag', sa.String(length=255), nullable=True),
    sa.Column('last_modified', sa.String(length=255), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('health', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connector_key', 'external_id', name='uq_source')
    )
    with op.batch_alter_table('job_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_sources_connector_key'), ['connector_key'], unique=False)

    op.create_table('learning_updates',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('before', sa.JSON(), nullable=False),
    sa.Column('after', sa.JSON(), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('rolled_back', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_updates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_updates_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('personal_context_items',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_json', sa.JSON(), nullable=True),
    sa.Column('last_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('can_use_for_application', sa.Boolean(), nullable=False),
    sa.Column('sensitivity_level', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('provenance', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('user_confirmed', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('personal_context_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personal_context_items_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_personal_context_items_user_id'), ['user_id'], unique=False)

    op.create_table('ranking_profiles',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('active_version_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ranking_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ranking_profiles_user_id'), ['user_id'], unique=False)

    op.create_table('standard_answers',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('question_key', sa.String(length=120), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('can_use_for_application', sa.Boolean(), nullable=False),
    sa.Column('sensitivity_level', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('provenance', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('user_confirmed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('standard_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_standard_answers_question_key'), ['question_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_standard_answers_user_id'), ['user_id'], unique=False)

    op.create_table('user_settings',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('notification_prefs', sa.JSON(), nullable=False),
    sa.Column('llm_cloud_opt_in', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('work_authorizations',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(length=120), nullable=True),
    sa.Column('needs_sponsorship', sa.Boolean(), nullable=True),
    sa.Column('sensitivity_level', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('provenance', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('user_confirmed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_authorizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_authorizations_user_id'), ['user_id'], unique=False)

    op.create_table('connector_failures',
    sa.Column('source_id', sa.String(length=32), nullable=True),
    sa.Column('connector_key', sa.String(length=40), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['job_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('connector_failures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connector_failures_source_id'), ['source_id'], unique=False)

    op.create_table('jobs',
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('source_job_id', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('normalized_title', sa.String(length=500), nullable=False),
    sa.Column('description_text', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('employment_type', sa.String(length=60), nullable=True),
    sa.Column('remote_mode', sa.String(length=20), nullable=True),
    sa.Column('official_source_url', sa.String(length=1000), nullable=True),
    sa.Column('canonical_application_url', sa.String(length=1000), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('application_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_status', sa.String(length=20), nullable=False),
    sa.Column('current_status', sa.String(length=30), nullable=False),
    sa.Column('source_priority', sa.Integer(), nullable=False),
    sa.Column('freshness_score', sa.Float(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('inbox_category', sa.String(length=20), nullable=False),
    sa.Column('duplicate_group_id', sa.String(length=32), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['job_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'source_job_id', name='uq_source_job')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_canonical_application_url'), ['canonical_application_url'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_current_status'), ['current_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_duplicate_group_id'), ['duplicate_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_inbox_category'), ['inbox_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_normalized_title'), ['normalized_title'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_source_id'), ['source_id'], unique=False)

    op.create_table('ranking_versions',
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('version_label', sa.String(length=40), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['ranking_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ranking_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ranking_versions_profile_id'), ['profile_id'], unique=False)

    op.create_table('resume_versions',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('direction', sa.String(length=80), nullable=True),
    sa.Column('is_base', sa.Boolean(), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('provenance', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('user_confirmed', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resume_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resume_versions_user_id'), ['user_id'], unique=False)

    op.create_table('source_sync_runs',
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('jobs_seen', sa.Integer(), nullable=False),
    sa.Column('jobs_new', sa.Integer(), nullable=False),
    sa.Column('jobs_updated', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['job_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_sync_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_sync_runs_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_sync_runs_source_id'), ['source_id'], unique=False)

    op.create_table('application_packets',
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('resume_version_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('packet_hash', sa.String(length=64), nullable=True),
    sa.Column('needs_cover_letter', sa.Boolean(), nullable=False),
    sa.Column('risks', sa.JSON(), nullable=False),
    sa.Column('uncertainties', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_packets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_packets_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_packets_packet_hash'), ['packet_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_packets_user_id'), ['user_id'], unique=False)

    op.create_table('duplicate_groups',
    sa.Column('canonical_job_id', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.String(length=120), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['canonical_job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eligibility_results',
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('jd_evidence', sa.JSON(), nullable=False),
    sa.Column('context_evidence', sa.JSON(), nullable=False),
    sa.Column('conflicts', sa.JSON(), nullable=False),
    sa.Column('unknowns', sa.JSON(), nullable=False),
    sa.Column('needs_user_confirmation', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eligibility_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eligibility_results_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eligibility_results_user_id'), ['user_id'], unique=False)

    op.create_table('job_embeddings',
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('vector', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_embeddings_job_id'), ['job_id'], unique=True)

    op.create_table('job_locations',
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('raw_text', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_locations_job_id'), ['job_id'], unique=False)

    op.create_table('job_matches',
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('ranking_version_id', sa.String(length=32), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('strategy', sa.String(length=20), nullable=False),
    sa.Column('why_recommended', sa.JSON(), nullable=False),
    sa.Column('why_not', sa.JSON(), nullable=False),
    sa.Column('suggested_minutes', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['ranking_version_id'], ['ranking_versions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'ranking_version_id', name='uq_match')
    )
    with op.batch_alter_table('job_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_matches_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_matches_total_score'), ['total_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_matches_user_id'), ['user_id'], unique=False)

    op.create_table('job_requirements',
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('field', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_requirements_job_id'), ['job_id'], unique=False)

    op.create_table('job_snapshots',
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source_status', sa.String(length=20), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_snapshots_job_id'), ['job_id'], unique=False)

    op.create_table('resume_sections',
    sa.Column('resume_version_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resume_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resume_sections_resume_version_id'), ['resume_version_id'], unique=False)

    op.create_table('user_feedback',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_feedback_user_id'), ['user_id'], unique=False)

    op.create_table('application_answers',
    sa.Column('packet_id', sa.String(length=32), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('field_type', sa.String(length=40), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('needs_user_input', sa.Boolean(), nullable=False),
    sa.Column('answer_source', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('provenance', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('user_confirmed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['packet_id'], ['application_packets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_answers_packet_id'), ['packet_id'], unique=False)

    op.create_table('applications',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('packet_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status_change_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['packet_id'], ['application_packets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_application')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_user_id'), ['user_id'], unique=False)

    op.create_table('generated_documents',
    sa.Column('packet_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('model_run_id', sa.String(length=32), nullable=True),
    sa.Column('user_confirmed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('provenance', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['packet_id'], ['application_packets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_documents_packet_id'), ['packet_id'], unique=False)

    op.create_table('match_dimensions',
    sa.Column('match_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('uncertainty', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['job_matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_dimensions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_dimensions_match_id'), ['match_id'], unique=False)

    op.create_table('resume_bullets',
    sa.Column('section_id', sa.String(length=32), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('tailored_text', sa.Text(), nullable=True),
    sa.Column('tailoring_rationale', sa.Text(), nullable=True),
    sa.Column('changes_factual_meaning', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('provenance', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('user_confirmed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['resume_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resume_bullets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resume_bullets_section_id'), ['section_id'], unique=False)

    op.create_table('application_confirmations',
    sa.Column('application_id', sa.String(length=32), nullable=False),
    sa.Column('packet_id', sa.String(length=32), nullable=False),
    sa.Column('packet_hash', sa.String(length=64), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by_user', sa.Boolean(), nullable=False),
    sa.Column('reviewed_answers_hash', sa.String(length=64), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['packet_id'], ['application_packets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_confirmations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_confirmations_application_id'), ['application_id'], unique=False)

    op.create_table('application_events',
    sa.Column('application_id', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_events_application_id'), ['application_id'], unique=False)

    op.create_table('email_events',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('application_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('message_ref', sa.String(length=255), nullable=True),
    sa.Column('needs_user_confirmation', sa.Boolean(), nullable=False),
    sa.Column('redacted_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_events_user_id'), ['user_id'], unique=False)

    op.create_table('match_evidence',
    sa.Column('dimension_id', sa.String(length=32), nullable=False),
    sa.Column('polarity', sa.String(length=10), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('origin', sa.String(length=40), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dimension_id'], ['match_dimensions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_evidence_dimension_id'), ['dimension_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_evidence_dimension_id'))

    op.drop_table('match_evidence')
    with op.batch_alter_table('email_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_events_user_id'))

    op.drop_table('email_events')
    with op.batch_alter_table('application_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_events_application_id'))

    op.drop_table('application_events')
    with op.batch_alter_table('application_confirmations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_confirmations_application_id'))

    op.drop_table('application_confirmations')
    with op.batch_alter_table('resume_bullets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_bullets_section_id'))

    op.drop_table('resume_bullets')
    with op.batch_alter_table('match_dimensions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_dimensions_match_id'))

    op.drop_table('match_dimensions')
    with op.batch_alter_table('generated_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_documents_packet_id'))

    op.drop_table('generated_documents')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_user_id'))
        batch_op.drop_index(batch_op.f('ix_applications_status'))
        batch_op.drop_index(batch_op.f('ix_applications_job_id'))

    op.drop_table('applications')
    with op.batch_alter_table('application_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_answers_packet_id'))

    op.drop_table('application_answers')
    with op.batch_alter_table('user_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_feedback_user_id'))

    op.drop_table('user_feedback')
    with op.batch_alter_table('resume_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_sections_resume_version_id'))

    op.drop_table('resume_sections')
    with op.batch_alter_table('job_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_snapshots_job_id'))

    op.drop_table('job_snapshots')
    with op.batch_alter_table('job_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_requirements_job_id'))

    op.drop_table('job_requirements')
    with op.batch_alter_table('job_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_matches_user_id'))
        batch_op.drop_index(batch_op.f('ix_job_matches_total_score'))
        batch_op.drop_index(batch_op.f('ix_job_matches_job_id'))

    op.drop_table('job_matches')
    with op.batch_alter_table('job_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_locations_job_id'))

    op.drop_table('job_locations')
    with op.batch_alter_table('job_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_embeddings_job_id'))

    op.drop_table('job_embeddings')
    with op.batch_alter_table('eligibility_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eligibility_results_user_id'))
        batch_op.drop_index(batch_op.f('ix_eligibility_results_job_id'))

    op.drop_table('eligibility_results')
    op.drop_table('duplicate_groups')
    with op.batch_alter_table('application_packets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_packets_user_id'))
        batch_op.drop_index(batch_op.f('ix_application_packets_packet_hash'))
        batch_op.drop_index(batch_op.f('ix_application_packets_job_id'))

    op.drop_table('application_packets')
    with op.batch_alter_table('source_sync_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_sync_runs_source_id'))
        batch_op.drop_index(batch_op.f('ix_source_sync_runs_idempotency_key'))

    op.drop_table('source_sync_runs')
    with op.batch_alter_table('resume_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_versions_user_id'))

    op.drop_table('resume_versions')
    with op.batch_alter_table('ranking_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ranking_versions_profile_id'))

    op.drop_table('ranking_versions')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_source_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_normalized_title'))
        batch_op.drop_index(batch_op.f('ix_jobs_inbox_category'))
        batch_op.drop_index(batch_op.f('ix_jobs_duplicate_group_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_current_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_content_hash'))
        batch_op.drop_index(batch_op.f('ix_jobs_company_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_canonical_application_url'))

    op.drop_table('jobs')
    with op.batch_alter_table('connector_failures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connector_failures_source_id'))

    op.drop_table('connector_failures')
    with op.batch_alter_table('work_authorizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_authorizations_user_id'))

    op.drop_table('work_authorizations')
    op.drop_table('user_settings')
    with op.batch_alter_table('standard_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_standard_answers_user_id'))
        batch_op.drop_index(batch_op.f('ix_standard_answers_question_key'))

    op.drop_table('standard_answers')
    with op.batch_alter_table('ranking_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ranking_profiles_user_id'))

    op.drop_table('ranking_profiles')
    with op.batch_alter_table('personal_context_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personal_context_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_personal_context_items_key'))

    op.drop_table('personal_context_items')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('learning_updates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_updates_user_id'))

    op.drop_table('learning_updates')
    with op.batch_alter_table('job_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_sources_connector_key'))

    op.drop_table('job_sources')
    with op.batch_alter_table('email_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_connections_user_id'))

    op.drop_table('email_connections')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_user_id'))

    op.drop_table('documents')
    with op.batch_alter_table('company_domains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_domains_company_id'))

    op.drop_table('company_domains')
    with op.batch_alter_table('company_career_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_career_pages_company_id'))

    op.drop_table('company_career_pages')
    with op.batch_alter_table('company_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_aliases_company_id'))
        batch_op.drop_index(batch_op.f('ix_company_aliases_alias'))

    op.drop_table('company_aliases')
    with op.batch_alter_table('candidate_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_skills_user_id'))
        batch_op.drop_index(batch_op.f('ix_candidate_skills_name'))

    op.drop_table('candidate_skills')
    with op.batch_alter_table('candidate_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_projects_user_id'))

    op.drop_table('candidate_projects')
    with op.batch_alter_table('candidate_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_profiles_user_id'))

    op.drop_table('candidate_profiles')
    with op.batch_alter_table('candidate_experiences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_experiences_user_id'))

    op.drop_table('candidate_experiences')
    with op.batch_alter_table('candidate_education', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_education_user_id'))

    op.drop_table('candidate_education')
    with op.batch_alter_table('application_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_preferences_user_id'))

    op.drop_table('application_preferences')
    op.drop_table('users')
    op.drop_table('model_runs')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_normalized_name'))
        batch_op.drop_index(batch_op.f('ix_companies_name'))

    op.drop_table('companies')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
