"""apply queue + ammo blocks

Revision ID: 66c10fba84b2
Revises: 65256e678135
Create Date: 2026-07-22 12:40:58.383421
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '66c10fba84b2'
down_revision: Union[str, None] = '65256e678135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ammo_blocks',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('direction', sa.String(length=80), nullable=True),
    sa.Column('variant_of', sa.String(length=32), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contains_metrics', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('provenance', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('user_confirmed', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['variant_of'], ['ammo_blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ammo_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ammo_blocks_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_ammo_blocks_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_ammo_blocks_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ammo_blocks_variant_of'), ['variant_of'], unique=False)

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('queue_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('queue_priority', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_applications_queued_at'), ['queued_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_queued_at'))
        batch_op.drop_column('queue_priority')
        batch_op.drop_column('queue_note')
        batch_op.drop_column('queued_at')

    with op.batch_alter_table('ammo_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ammo_blocks_variant_of'))
        batch_op.drop_index(batch_op.f('ix_ammo_blocks_user_id'))
        batch_op.drop_index(batch_op.f('ix_ammo_blocks_direction'))
        batch_op.drop_index(batch_op.f('ix_ammo_blocks_category'))

    op.drop_table('ammo_blocks')
    # ### end Alembic commands ###
