"""company-tier-centric inbox tables

Revision ID: a8360d4235b7
Revises: dcc651cf609b
Create Date: 2026-07-22 22:06:29.216222
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a8360d4235b7'
down_revision: Union[str, None] = 'dcc651cf609b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_application_policies',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('recommended_limit', sa.Integer(), nullable=False),
    sa.Column('user_override_limit', sa.Integer(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_policy')
    )
    with op.batch_alter_table('company_application_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_application_policies_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_application_policies_user_id'), ['user_id'], unique=False)

    op.create_table('company_watchlists',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('priority_note', sa.Text(), nullable=True),
    sa.Column('muted', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_watch')
    )
    with op.batch_alter_table('company_watchlists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_watchlists_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_watchlists_user_id'), ['user_id'], unique=False)

    op.create_table('recommended_application_sets',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('calculation_version', sa.String(length=30), nullable=False),
    sa.Column('ranking_mode', sa.String(length=20), nullable=False),
    sa.Column('company_tier', sa.String(length=4), nullable=False),
    sa.Column('company_tier_display', sa.String(length=40), nullable=False),
    sa.Column('provisional', sa.Boolean(), nullable=False),
    sa.Column('recommended_limit', sa.Integer(), nullable=False),
    sa.Column('recommended_count', sa.Integer(), nullable=False),
    sa.Column('excluded_count', sa.Integer(), nullable=False),
    sa.Column('already_applied_count', sa.Integer(), nullable=False),
    sa.Column('over_limit', sa.Boolean(), nullable=False),
    sa.Column('evidence_snapshot', sa.JSON(), nullable=False),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_override', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommended_application_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommended_application_sets_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommended_application_sets_user_id'), ['user_id'], unique=False)

    op.create_table('company_role_rankings',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('company_internal_rank', sa.Integer(), nullable=False),
    sa.Column('global_rank', sa.Integer(), nullable=False),
    sa.Column('application_priority', sa.Float(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_role_rank')
    )
    with op.batch_alter_table('company_role_rankings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_role_rankings_application_priority'), ['application_priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_role_rankings_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_role_rankings_global_rank'), ['global_rank'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_role_rankings_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_role_rankings_user_id'), ['user_id'], unique=False)

    op.create_table('recommended_application_set_items',
    sa.Column('set_id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('global_rank', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('role_family', sa.String(length=40), nullable=False),
    sa.Column('role_band', sa.String(length=4), nullable=False),
    sa.Column('similarity_group_key', sa.String(length=40), nullable=True),
    sa.Column('redundancy_risk', sa.Float(), nullable=False),
    sa.Column('application_priority', sa.Float(), nullable=False),
    sa.Column('company_platform_value', sa.Float(), nullable=False),
    sa.Column('role_strategic_value', sa.Float(), nullable=False),
    sa.Column('current_candidate_fit', sa.Float(), nullable=False),
    sa.Column('team_project_quality', sa.Float(), nullable=False),
    sa.Column('career_optionality', sa.Float(), nullable=False),
    sa.Column('evidence_coverage', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('superseded_by', sa.String(length=500), nullable=True),
    sa.Column('duplicates_applied_role', sa.Boolean(), nullable=False),
    sa.Column('has_official_link', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['recommended_application_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommended_application_set_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommended_application_set_items_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommended_application_set_items_set_id'), ['set_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommended_application_set_items_similarity_group_key'), ['similarity_group_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommended_application_set_items_status'), ['status'], unique=False)

    op.create_table('role_similarity_groups',
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('group_key', sa.String(length=40), nullable=False),
    sa.Column('representative_job_id', sa.String(length=32), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('max_redundancy_risk', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['representative_job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role_similarity_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_similarity_groups_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_similarity_groups_group_key'), ['group_key'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_similarity_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_similarity_groups_group_key'))
        batch_op.drop_index(batch_op.f('ix_role_similarity_groups_company_id'))

    op.drop_table('role_similarity_groups')
    with op.batch_alter_table('recommended_application_set_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommended_application_set_items_status'))
        batch_op.drop_index(batch_op.f('ix_recommended_application_set_items_similarity_group_key'))
        batch_op.drop_index(batch_op.f('ix_recommended_application_set_items_set_id'))
        batch_op.drop_index(batch_op.f('ix_recommended_application_set_items_job_id'))

    op.drop_table('recommended_application_set_items')
    with op.batch_alter_table('company_role_rankings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_role_rankings_user_id'))
        batch_op.drop_index(batch_op.f('ix_company_role_rankings_job_id'))
        batch_op.drop_index(batch_op.f('ix_company_role_rankings_global_rank'))
        batch_op.drop_index(batch_op.f('ix_company_role_rankings_company_id'))
        batch_op.drop_index(batch_op.f('ix_company_role_rankings_application_priority'))

    op.drop_table('company_role_rankings')
    with op.batch_alter_table('recommended_application_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommended_application_sets_user_id'))
        batch_op.drop_index(batch_op.f('ix_recommended_application_sets_company_id'))

    op.drop_table('recommended_application_sets')
    with op.batch_alter_table('company_watchlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_watchlists_user_id'))
        batch_op.drop_index(batch_op.f('ix_company_watchlists_company_id'))

    op.drop_table('company_watchlists')
    with op.batch_alter_table('company_application_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_application_policies_user_id'))
        batch_op.drop_index(batch_op.f('ix_company_application_policies_company_id'))

    op.drop_table('company_application_policies')
    # ### end Alembic commands ###
