"""widen ranking display columns for postgres

Revision ID: dcc651cf609b
Revises: 3f2f9b30e4a1
Create Date: 2026-07-22 15:23:38.586386
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dcc651cf609b'
down_revision: Union[str, None] = '3f2f9b30e4a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_priority_scores', schema=None) as batch_op:
        batch_op.alter_column('company_tier_display',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=40),
               existing_nullable=False)
        batch_op.alter_column('opportunity_estimate',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('recommendation',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=60),
               existing_nullable=False)
        batch_op.alter_column('interaction_rule',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_priority_scores', schema=None) as batch_op:
        batch_op.alter_column('interaction_rule',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('recommendation',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
        batch_op.alter_column('opportunity_estimate',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.alter_column('company_tier_display',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
