"""opportunity viability, action urgency, application effort

Revision ID: f60de245306b
Revises: a8360d4235b7
Create Date: 2026-07-24 13:58:34.116783
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f60de245306b'
down_revision: Union[str, None] = 'a8360d4235b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_priority_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'opportunity_viability', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column(
            'action_urgency', sa.String(length=120), nullable=False, server_default=''))
        batch_op.add_column(sa.Column(
            'application_effort_minutes', sa.Integer(), nullable=False, server_default='20'))
        batch_op.drop_column('opportunity_estimate')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_priority_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opportunity_estimate', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_column('application_effort_minutes')
        batch_op.drop_column('action_urgency')
        batch_op.drop_column('opportunity_viability')

    # ### end Alembic commands ###
